steps:
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['run' , 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us.gcr.io/$PROJECT_ID/heracles/faker:latest',
      '-t',
      'us.gcr.io/$PROJECT_ID/heracles/faker:$SHORT_SHA',
      '-f',
      'Dockerfile-cloudbuild',
      '/workspace'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us.gcr.io/$PROJECT_ID/heracles/faker:latest'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us.gcr.io/$PROJECT_ID/heracles/faker:$SHORT_SHA'
    ]
  - name: 'gcr.io/cloud-builders/kubectl'
    env: [
      'CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID',
      'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    ]
    args: [
      '-n',
      'heracles',
      'set',
      'image',
      'deploy/api-faker',
      'faker=us.gcr.io/$PROJECT_ID/heracles/faker:$SHORT_SHA',
      '--record'
    ]
